### PR TITLE
Make image upload optional

### PR DESCRIPTION
**Pull request by apirobot**
If you want the toolbar has only image links:

```javascript
toolbars: {
  imagelink: true,
  imageupload: false
}
```

If you want the toolbar has only image uploading:

```javascript
toolbars: {
  imagelink: false,
  imageupload: true
}
```

If you want the toolbar has image links and image uploading:

```javascript
toolbars: {
  imagelink: true,
  imageupload: true
}
```

### CODE REVIEW

**Comment by crberube** [comment]
What needs to happen in order to get this merged? It would be very helpful for those who do not want to implement image upload functionality without leaving a broken UI option.

**Comment by ChadTaljaardt** [comment]
@hinesboy Are you interested in this functionality? I can bring it up to date with the codebase if you are willing to merge this feature. This PR is from 2018 so i don't want to waste my time if you don't want this feature.

**Comment by selimdoyranli** [comment]
+1

**Comment by ygj6** [comment]
Sorry, this PR has been in the past too long, and the current one cannot be merged, and it needs to be closed.

Welcome to submit a new PR on the latest master branch, I will review it as soon as possible.

**Pull request closed without merging**
